name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Connect to Droplet & Deploy
        run: |
          sshpass -p "${{ secrets.DO_DROPLET_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_DROPLET_USER }}@${{ secrets.DO_DROPLET_IP }} << 'EOF'
            cd /root/sgmm-api

            # Store environment variables in .env file
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
            echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" >> .env

            # Export env variables globally (optional)
            OPENAI_API_KEY=${{ vars.OPENAI_API_KEY }}
            MISTRAL_API_KEY=${{ vars.MISTRAL_API_KEY }}

            docker-compose down

            git pull origin main

            # Rebuild and recreate containers
            docker-compose up -d --build --force-recreate
          EOF
