name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Connect to Droplet & Deploy
        run: |
          sshpass -p "${{ secrets.DO_DROPLET_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DO_DROPLET_USER }}@${{ secrets.DO_DROPLET_IP }} << 'EOF'
            cd /root/sgmm-api
            git pull origin main
            docker-compose up -d --build
          EOF
